apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: 748735308412.dkr.ecr.us-west-2.amazonaws.com/client:latest
        env:
          - name: SERVER_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SERVER_HOST
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SERVER_PORT
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: ClusterIP
  selector:
      app: client
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001