apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}-service
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
